print('Hello world!')
print('Este é meu primeiro código em Python')


print('A: Você sabe por que a gente sonha?')
print('B: Ainda não existe uma reposta definitiva')
print('A: Mas o cérebro continua ativo enquanto dormimos?')
print('B: Sim, ele continua trabalhando')
print('A: Então é por isso que temos sonhos?')
print('B: Pode ser uma das razões')
print('A: A gente sonha toda noite?')
print('B: Provavelmente, mas nem sempre lembramos')
print('A: E por que nos esquecemos tão rápido?')
print('B: Nosso cérebro nem sempre armazena o sonho')
print('A: E dá pra controlar um sonho?')
print('B: Algumas pessoas conseguem')
print('A: Isso se chama sonho lúcido?')
print('B: Exatamente')
print('A: Então dá pra saber que estou sonhando?')
print('B: Sim, durante esses sonhos lúcidos')
print('A: Que estranho')
print('B: E muito interessante também')
